# Rust formatting configuration
unstable_features = true
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"

# Imports
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 80
normalize_comments = true
normalize_doc_attributes = true

# Other
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
