# SPDX-License-Identifier: MIT
---
name: Security - Dependency Review
# Reviews dependency changes in PRs for known security vulnerabilities.

"on":
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: ðŸ” Dependency Review
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    concurrency:
      group: dependency-review-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Harden Runner
        # yamllint disable-line rule:line-length
        uses: lgtm-hq/lgtm-ci/.github/actions/harden-runner@v0
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            codeload.github.com:443
            objects.githubusercontent.com:443
            api.deps.dev:443
            api.securityscorecards.dev:443

      - name: Checkout
        # yamllint disable-line rule:line-length
        uses: lgtm-hq/lgtm-ci/.github/actions/secure-checkout@v0

      - name: Dependency review
        # yamllint disable-line rule:line-length
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        continue-on-error: >-
          ${{ github.event.pull_request.head.repo.fork == true }}
        with:
          fail-on-severity: high
          # yamllint disable-line rule:line-length
          comment-summary-in-pr: >-
            ${{ github.event.pull_request.head.repo.fork == false }}
          allow-ghsas: true
